dist: trusty

language: php

php:
  - 7.0

sudo: required

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
    - python

before_install:
  - wget http://packages.couchbase.com/releases/3.1.0/couchbase-server-enterprise_3.1.0-ubuntu14.04_amd64.deb
  - dpkg-deb -x couchbase-server-enterprise_3.1.0-ubuntu14.04_amd64.deb $HOME
  - cd $HOME/opt/couchbase
  - ./bin/install/reloc.sh `pwd`
  - ./bin/couchbase-server -- -noinput -detached
  - sleep 20
  - ./bin/couchbase-cli cluster-init -c 127.0.0.1:8091  --cluster-init-username=Administrator --cluster-init-password=Administrator --cluster-init-port=8091 --cluster-init-ramsize=1024
  - ./bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=test --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=512  --bucket-replica=1 -u Administrator -p Administrator

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi


script:
  - phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi